version: 2.1
orbs:
  cypress: cypress-io/cypress@3.1.3
workflows:
  build:
    jobs:
      - cypress/run:
          cypress-command: 'npx cypress run --record --key f4466038-70c2-4688-9ed9-106bf013cd75'
